volumes:
  cache:
  wallet_writer_data:
  history_writer_data:

services:

  #
  # shared services
  #

  message_broker:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/message_broker/Dockerfile
    volumes:
      - ./message_broker/nats-server.conf:/etc/nats/nats-server.conf:ro
    ports:
      - "4222:4222/tcp"
      - "6222:6222/tcp"
      - "8222:8222/tcp"

  cache:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/cache/Dockerfile
    volumes:
      - cache:/data
    ports:
      - "6379:6379/tcp"

  #
  # global event log
  #

  history_writer_datastore:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/datastore/Dockerfile
    volumes:
      - history_writer_data:/var/lib/postgresql/data
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_PASSWORD: "Password1"
      POSTGRES_DB: "datastore"

  history_writer_service:
    restart: always
    stop_signal: SIGINT
    build:
      context: ../
      dockerfile: ./docker/service/Dockerfile
      args:
        - CMD_NAME=history_writer
    environment:
      POSTGRES_HOST: "history_writer_datastore"
      ENTITY_ID: "29p8aA0XrY2slsqmEyNzBlS7f64"
    depends_on:
      history_writer_datastore:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      cache:
        condition: service_healthy

  #
  # wallet domain
  #

  wallet_writer_datastore:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/datastore/Dockerfile
    volumes:
      - wallet_writer_data:/var/lib/postgresql/data
    environment:
      TIMESCALEDB_TELEMETRY: "off"
      POSTGRES_PASSWORD: "Password1"
      POSTGRES_DB: "datastore"

  wallet_writer_service:
    restart: always
    stop_signal: SIGINT
    build:
      context: ../
      dockerfile: ./docker/service/Dockerfile
      args:
        - CMD_NAME=wallet_writer
    environment:
      POSTGRES_HOST: "wallet_writer_datastore"
      ENTITY_ID: "28skwt5B8zTrs6AqBWrSgCHLcRL"
    depends_on:
      wallet_writer_datastore:
        condition: service_healthy
      message_broker:
        condition: service_healthy
      cache:
        condition: service_healthy

  wallet_server_service:
    restart: always
    stop_signal: SIGINT
    build:
      context: ../
      dockerfile: ./docker/service/Dockerfile
      args:
        - CMD_NAME=wallet_server
    ports:
      - "80:80/tcp"
    depends_on:
      message_broker:
        condition: service_healthy
      cache:
        condition: service_healthy
